name: Test, build a docker image and push that to the Dockerhub
on:
  push:
    branches:
      - dockerhubcicd
    paths-ignore:
      - 'README.md'

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: pytest         