name: Test and Deploy to Heroku

on:
  push:
    branches:
      - main  # Ветка, на которую будет происходить деплой

jobs:
  deploy:
    runs-on: ubuntu-latest  # Используем Ubuntu для CI/CD

    steps:
    # Шаг 1: Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v4
    #Шаг 1.1 Убираем ошибку shallow clone
    - name: Convert shallow clone to full
      run: git fetch --all --unshallow
    # Шаг 2: Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Шаг 3: Устанавливаем зависимости
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Шаг 4: Запускаем тесты с pytest
    - name: Run tests with pytest
      run: |
        pytest
    # Шаг 5: деплой на хероку
    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
        git push heroku HEAD:main -f
