name: Test and Deploy to Heroku

on:
  push:
    branches:
      - main  # Ветка, на которую будет происходить деплой

jobs:
  deploy:
    runs-on: ubuntu-latest  # Используем Ubuntu для CI/CD

    steps:
    # Шаг 1: Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v4

    # Шаг 2: Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Шаг 3: Устанавливаем зависимости
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Шаг 4: Запускаем тесты с pytest
    - name: Run tests with pytest
      run: |
        pytest
    # Шаг 5: Логинимся в Heroku с использованием API токена
    - name: Login to Heroku
      uses: akshnz/heroku-cli-action@v1
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}  # Токен API Heroku

    # Шаг 6: Делаем деплой на Heroku
    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku main
